#!/bin/bash
#Install Jenkins
sudo yum update –y
sleep 30
sudo wget -O /etc/yum.repos.d/jenkins.repo     https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
sudo yum upgrade
sudo dnf install java-17-amazon-corretto -y
sleep 30
sudo yum install jenkins -y
sleep 30
sudo systemctl enable jenkins
sudo systemctl start jenkins
sudo systemctl status jenkins

#Install Terraform
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
sudo yum -y install terraform
sleep 30
terraform --version