variable "ami_id" {}
variable "instance_type" {}
variable "tag_name" {}
variable "public_key" {}
variable "subnet_id" {}
variable "sg_for_jenkins" {}
variable "enable_public_ip_address" {}
variable "user_data_install_jenkins" {}

output "ssh_connection_string_for_ec2" {
  value = format("%s%s", "ssh -i /Users/sandy4v/Desktop/Github/AWS/ssh_keys/aws_jen_tf_ssh_key ec2-user@", aws_instance.EC2_Terraform_Jenkins.public_ip)
  # ssh -i /Users/sandy4v/Desktop/Github/AWS/ssh_keys/aws_jen_tf_ssh_key ec2-user@<public dns ip>  
}

output "EC2_Terraform_Jenkins_id" {
  value = aws_instance.EC2_Terraform_Jenkins.id
}

output "AWS_TF_Jen_ec2_instance_public_ip" {
  value = aws_instance.EC2_Terraform_Jenkins.public_ip
}

resource "aws_instance" "EC2_Terraform_Jenkins" {
  depends_on = [aws_key_pair.jenkins_ec2_instance_public_key]  # Ensure key pair exists first
  ami           = var.ami_id
  instance_type = var.instance_type
  tags = {
    Name = var.tag_name
  }
  key_name                    = "aws_jen_tf_ssh_key" # This is a private key generated by ssh-keygen and must be imported in AWS prior to using it here. 
                                                      #aws ec2 import-key-pair --key-name aws_jen_tf_ssh_key --public-key-material "$(cat ~/.ssh/id_rsa.pub)"
 
  subnet_id                   = var.subnet_id
  vpc_security_group_ids      = var.sg_for_jenkins
  associate_public_ip_address = var.enable_public_ip_address

  user_data = var.user_data_install_jenkins

  metadata_options {
    http_endpoint = "enabled"  # Enable the IMDSv2 endpoint
    http_tokens   = "required" # Require the use of IMDSv2 tokens
  }
}

resource "aws_key_pair" "jenkins_ec2_instance_public_key" {
  key_name   = "aws_jen_tf_ssh_key"
  public_key = var.public_key
}